name: build
# Export solution from DEV environment
# unpack it and prepare, commit and push a git branch with the changes
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: ALMLab
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
env:
#edit your values here
  ENVIRONMENT_URL: 'https://orgb1369bf8.crm11.dynamics.com'
  CLIENT_ID: '3df282dd-9d42-448b-b9e4-fac8beadd2a0'
  TENANT_ID: 'e54a0000-05b8-4a62-b9bb-5ea5fdbb5178'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:  
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: set build date
      run: |
        echo "BUILD_DATE1=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
        echo "${{env}}"
        echo "BUILD_DATE2=$(date +%Y%M%d)" >> ${GITHUB_ENV}
        echo "${{env}}"

    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
    - name: Echo current date
      run: echo "${{env}}" 

    - name: Echo context
      run: echo "${{github}}"

    - name: Echo env
      run: echo "${{env}}"
